version: "3.7"

logging:
  driver: "awslogs"
  options:
    awslogs-region: us-east-1
    awslogs-group: Eth2-docker

services:
  geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    restart: always
    hostname: geth
    command: --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts="*" --allow-insecure-unlock --http.api="db,eth,net,web3,personal"
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 127.0.0.1:8545:8545
    volumes:
      - ./data/geth:/root/.ethereum
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-east-1
        awslogs-group: Eth2-geth

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG}
    restart: always
    hostname: beacon-chain
    depends_on:
      - geth
    command: --config-file=/config/beacon.yaml
    ports:
      - 127.0.0.1:4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    networks:
      default:
        aliases:
          - prysm_beacon_slasher
    volumes:
      - ./config/prysm/slasher/beacon.yaml:/config/beacon.yaml:ro
      - ./data/prysm/beacon-slasher:/data
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-east-1
        awslogs-group: Eth2-beacon

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
    restart: on-failure
    hostname: validator
    depends_on:
      - beacon
    command: --config-file=/config/validator.yaml
    volumes:
      - ./config/prysm/validator.yaml:/config/validator.yaml:ro
      - ./data/prysm/validator:/data
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-east-1
        awslogs-group: Eth2-validator

  slasher:
    image: gcr.io/prysmaticlabs/prysm/slasher:${PRYSM_DOCKER_TAG}
    restart: always
    hostname: slasher
    depends_on:
      - beacon
    command: --config-file=/config/slasher.yaml
    volumes:
      - ./config/prysm/slasher/slasher.yaml:/config/slasher.yaml:ro
      - ./data/prysm/slasher:/data
    logging:
      driver: "awslogs"
      options:
        awslogs-region: us-east-1
        awslogs-group: Eth2-slasher


# EOF
